version: '3.1'

services:
  mysql_db:
    image: mysql:5.7
    volumes: 
      - /home/mateo-pc/Desktop/type-pruebas/mysql/init.sql/:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: superu
      MYSQL_USER: superu
      MYSQL_ROOT_PASSWORD: Argul1266
      MYSQL_PASSWORD: Argul1266